/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlacementReadinessRouteImport } from './routes/placement-readiness'
import { Route as PlacementJourneyRouteImport } from './routes/placement-journey'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LevelsRouteImport } from './routes/levels'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackOssRouteImport } from './routes/track.oss'
import { Route as TrackDsaRouteImport } from './routes/track.dsa'
import { Route as TrackDevRouteImport } from './routes/track.dev'
import { Route as TrackAptitudeRouteImport } from './routes/track.aptitude'
import { Route as TrackAiRouteImport } from './routes/track.ai'

const PlacementReadinessRoute = PlacementReadinessRouteImport.update({
  id: '/placement-readiness',
  path: '/placement-readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementJourneyRoute = PlacementJourneyRouteImport.update({
  id: '/placement-journey',
  path: '/placement-journey',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsRoute = LevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOssRoute = TrackOssRouteImport.update({
  id: '/track/oss',
  path: '/track/oss',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackDsaRoute = TrackDsaRouteImport.update({
  id: '/track/dsa',
  path: '/track/dsa',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackDevRoute = TrackDevRouteImport.update({
  id: '/track/dev',
  path: '/track/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackAptitudeRoute = TrackAptitudeRouteImport.update({
  id: '/track/aptitude',
  path: '/track/aptitude',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackAiRoute = TrackAiRouteImport.update({
  id: '/track/ai',
  path: '/track/ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/connectors': typeof ConnectorsRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/levels': typeof LevelsRoute
  '/login': typeof LoginRoute
  '/placement-journey': typeof PlacementJourneyRoute
  '/placement-readiness': typeof PlacementReadinessRoute
  '/track/ai': typeof TrackAiRoute
  '/track/aptitude': typeof TrackAptitudeRoute
  '/track/dev': typeof TrackDevRoute
  '/track/dsa': typeof TrackDsaRoute
  '/track/oss': typeof TrackOssRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/connectors': typeof ConnectorsRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/levels': typeof LevelsRoute
  '/login': typeof LoginRoute
  '/placement-journey': typeof PlacementJourneyRoute
  '/placement-readiness': typeof PlacementReadinessRoute
  '/track/ai': typeof TrackAiRoute
  '/track/aptitude': typeof TrackAptitudeRoute
  '/track/dev': typeof TrackDevRoute
  '/track/dsa': typeof TrackDsaRoute
  '/track/oss': typeof TrackOssRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/connectors': typeof ConnectorsRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/levels': typeof LevelsRoute
  '/login': typeof LoginRoute
  '/placement-journey': typeof PlacementJourneyRoute
  '/placement-readiness': typeof PlacementReadinessRoute
  '/track/ai': typeof TrackAiRoute
  '/track/aptitude': typeof TrackAptitudeRoute
  '/track/dev': typeof TrackDevRoute
  '/track/dsa': typeof TrackDsaRoute
  '/track/oss': typeof TrackOssRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/connectors'
    | '/dashboard'
    | '/leaderboard'
    | '/levels'
    | '/login'
    | '/placement-journey'
    | '/placement-readiness'
    | '/track/ai'
    | '/track/aptitude'
    | '/track/dev'
    | '/track/dsa'
    | '/track/oss'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/connectors'
    | '/dashboard'
    | '/leaderboard'
    | '/levels'
    | '/login'
    | '/placement-journey'
    | '/placement-readiness'
    | '/track/ai'
    | '/track/aptitude'
    | '/track/dev'
    | '/track/dsa'
    | '/track/oss'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/connectors'
    | '/dashboard'
    | '/leaderboard'
    | '/levels'
    | '/login'
    | '/placement-journey'
    | '/placement-readiness'
    | '/track/ai'
    | '/track/aptitude'
    | '/track/dev'
    | '/track/dsa'
    | '/track/oss'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  ConnectorsRoute: typeof ConnectorsRoute
  DashboardRoute: typeof DashboardRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LevelsRoute: typeof LevelsRoute
  LoginRoute: typeof LoginRoute
  PlacementJourneyRoute: typeof PlacementJourneyRoute
  PlacementReadinessRoute: typeof PlacementReadinessRoute
  TrackAiRoute: typeof TrackAiRoute
  TrackAptitudeRoute: typeof TrackAptitudeRoute
  TrackDevRoute: typeof TrackDevRoute
  TrackDsaRoute: typeof TrackDsaRoute
  TrackOssRoute: typeof TrackOssRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/placement-readiness': {
      id: '/placement-readiness'
      path: '/placement-readiness'
      fullPath: '/placement-readiness'
      preLoaderRoute: typeof PlacementReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement-journey': {
      id: '/placement-journey'
      path: '/placement-journey'
      fullPath: '/placement-journey'
      preLoaderRoute: typeof PlacementJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels': {
      id: '/levels'
      path: '/levels'
      fullPath: '/levels'
      preLoaderRoute: typeof LevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/oss': {
      id: '/track/oss'
      path: '/track/oss'
      fullPath: '/track/oss'
      preLoaderRoute: typeof TrackOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/dsa': {
      id: '/track/dsa'
      path: '/track/dsa'
      fullPath: '/track/dsa'
      preLoaderRoute: typeof TrackDsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/dev': {
      id: '/track/dev'
      path: '/track/dev'
      fullPath: '/track/dev'
      preLoaderRoute: typeof TrackDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/aptitude': {
      id: '/track/aptitude'
      path: '/track/aptitude'
      fullPath: '/track/aptitude'
      preLoaderRoute: typeof TrackAptitudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/ai': {
      id: '/track/ai'
      path: '/track/ai'
      fullPath: '/track/ai'
      preLoaderRoute: typeof TrackAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  ConnectorsRoute: ConnectorsRoute,
  DashboardRoute: DashboardRoute,
  LeaderboardRoute: LeaderboardRoute,
  LevelsRoute: LevelsRoute,
  LoginRoute: LoginRoute,
  PlacementJourneyRoute: PlacementJourneyRoute,
  PlacementReadinessRoute: PlacementReadinessRoute,
  TrackAiRoute: TrackAiRoute,
  TrackAptitudeRoute: TrackAptitudeRoute,
  TrackDevRoute: TrackDevRoute,
  TrackDsaRoute: TrackDsaRoute,
  TrackOssRoute: TrackOssRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
